# Clase 11: Introducción a pandas

In [1]:
# Primero, importamos pandas (por convención se usa el alias pd)
import pandas as pd
import numpy as np  # También importamos numpy que suele usarse junto con pandas

# Data frame

In [2]:
# Creación de un DataFrame desde un arreglo
data = {
    'Nombre': ['Juan', 'María', 'Carlos', 'Ana'],
    'Edad': [25, 32, 28, 35],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']
}

### Crear el dataframe apartir de un diccionario
df = pd.DataFrame(data)
df

   Nombre  Edad     Ciudad
0    Juan    25     Madrid
1   María    32  Barcelona
2  Carlos    28   Valencia
3     Ana    35    Sevilla

* Los dataframes están copuestos de series, que podría entenderse como una columna que forma parte del excel.

In [3]:
# Creación de una Serie
edades = pd.Series([25, 32, 28, 35], name='Edad')
edades

0    25
1    32
2    28
3    35
Name: Edad, dtype: int64

## Lectura y escritura de datos

* `df.to_csv` guardar los datos en un csv.

In [4]:
# Lectura de un archivo CSV (comentar para el ejemplo, ya que no existe el archivo)
# df = pd.read_csv('datos.csv')

# Escritura a CSV
df.to_csv('datos_ejemplo2.csv', index=False)

# Lectura desde Excel
# df = pd.read_excel('datos.xlsx')

# Lectura desde una URL
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv'
iris = pd.read_csv(url)
iris.head()  # Muestra las primeras 5 filas

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Exporación básica de datos

* La función `display()` se usa para mostrar objetos de forma más rica e interactiva en entornos como `Jupyter Notebook`, `Google Colab` o cualquier entorno basado en `IPython`.
* valores unicos --> `display(iris['species'].unique())`

In [6]:
from IPython.display import display

# Información básica del DataFrame
print("* Información del DataFrame:")
display(iris.info())

# Estadísticas descriptivas
print("\n* Estadísticas descriptivas:")
display(iris.describe())

# Primeras filas
print("\n* Primeras 3 filas:")
display(iris.head(3))

# Últimas filas
print("\n* Últimas 2 filas:")
display(iris.tail(2))

# Forma del DataFrame (filas, columnas)
print("\n* Forma del DataFrame:")
display(iris.shape)

# Nombres de columnas
print("\n* Nombres de columnas:")
display(iris.columns)

# Valores únicos en una columna
print("\n* Especies únicas:")
display(iris['species'].unique())

* Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

None

* Estadísticas descriptivas:

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

* Primeras 3 filas:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

* Últimas 2 filas:

     sepal_length  sepal_width  petal_length  petal_width    species
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

* Forma del DataFrame:

(150, 5)

* Nombres de columnas:

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

* Especies únicas:

array(['setosa', 'versicolor', 'virginica'], dtype=object)

## Seleccion y filtrado de datos

In [9]:
### Selección de una columna (devuelve Series)
display(iris['sepal_length'])

### Selección de múltiples columnas
display(iris[['sepal_length', 'species']])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

     sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [17]:
### Selección por posición (iloc)
print("Primeras 3 filas, primeras 2 columnas:")
display(iris.iloc[:3, :2])

### Selección por etiqueta (loc), del segundo registro al 3 registro sobre sepal y species
print("\nFiltrado por índice y columnas:")
display(iris.loc[2:5, ['sepal_length', 'species']])

Primeras 3 filas, primeras 2 columnas:

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

Filtrado por índice y columnas:

   sepal_length species
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa

* Esta muy interesante esto `iris.query`

In [18]:
### Filtrado con condiciones
print("\nPlantas con sépalo mayor a 5 cm:")
display(iris[iris['sepal_length'] > 5])

# Filtrado con múltiples condiciones
print("\nPlantas con sépalo >5 y pétalo <1.5:")
display(iris[(iris['sepal_length'] > 5) & (iris['petal_length'] < 1.5)])

# Query (filtrado con expresión de cadena)
print("\nUsando query:")
display(iris.query('sepal_length > 5 and petal_length < 1.5'))

Plantas con sépalo mayor a 5 cm:

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

Plantas con sépalo >5 y pétalo <1.5:

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
28           5.2          3.4           1.4          0.2  setosa
33           5.5          4.2           1.4          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa

Usando query:

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
28           5.2          3.4           1.4          0.2  setosa
33           5.5          4.2           1.4          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa

## Manipulación de datos

In [19]:
### Añadir nueva columna
iris['sepal_area'] = iris['sepal_length'] * iris['sepal_width']
display(iris.head())

### Renombrar columnas
iris_renombrado = iris.rename(columns={
    'sepal_length': 'longitud_sepalo',
    'sepal_width': 'ancho_sepalo'
})
display(iris_renombrado.head(2))

### Eliminar columnas
iris_sin_area = iris.drop(columns=['sepal_area'])
display(iris_sin_area.head(2))

### Ordenar valores
print("Ordenado por longitud de sépalo descendente:")
display(iris.sort_values('sepal_length', ascending=False).head())

### Valores faltantes (aunque en este dataset no hay)
print("\nValores nulos por columna:")
display(iris.isnull().sum())

   sepal_length  sepal_width  petal_length  petal_width species  sepal_area
0           5.1          3.5           1.4          0.2  setosa       17.85
1           4.9          3.0           1.4          0.2  setosa       14.70
2           4.7          3.2           1.3          0.2  setosa       15.04
3           4.6          3.1           1.5          0.2  setosa       14.26
4           5.0          3.6           1.4          0.2  setosa       18.00

,longitud_sepalo,ancho_sepalo,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,setosa,17.85
1,4.9,3.0,1.4,0.2,setosa,14.70

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

Ordenado por longitud de sépalo descendente:

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
131,7.9,3.8,6.4,2.0,virginica,30.02
135,7.7,3.0,6.1,2.3,virginica,23.10
122,7.7,2.8,6.7,2.0,virginica,21.56
117,7.7,3.8,6.7,2.2,virginica,29.26
118,7.7,2.6,6.9,2.3,virginica,20.02

Valores nulos por columna:

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
sepal_area      0
dtype: int64

## Operaciones agrupadas

In [20]:
# GroupBy - Agrupación por especie
grupo_especies = iris.groupby('species')

# Estadísticas por grupo
print("Media por especie:")
display(grupo_especies.mean())

# Contar elementos por grupo
print("\nConteo por especie:")
display(grupo_especies.size())

# Aplicar múltiples funciones de agregación
print("\nMúltiples estadísticas:")
display(grupo_especies.agg(['mean', 'std', 'min', 'max']))

Media por especie:

            sepal_length  sepal_width  petal_length  petal_width  sepal_area
species
setosa             5.006        3.428         1.462        0.246     17.2578
versicolor         5.936        2.770         4.260        1.326     16.5262
virginica          6.588        2.974         5.552        2.026     19.6846

Conteo por especie:

species
setosa        50
versicolor    50
virginica     50
dtype: int64

Múltiples estadísticas:

           sepal_length                     sepal_width                      \
                   mean       std  min  max        mean       std  min  max
species
setosa            5.006  0.352490  4.3  5.8       3.428  0.379064  2.3  4.4
versicolor        5.936  0.516171  4.9  7.0       2.770  0.313798  2.0  3.4
virginica         6.588  0.635880  4.9  7.9       2.974  0.322497  2.2  3.8

           petal_length                     petal_width                      \
                   mean       std  min  max        mean       std  min  max
species
setosa            1.462  0.173664  1.0  1.9       0.246  0.105386  0.1  0.6
versicolor        4.260  0.469911  3.0  5.1       1.326  0.197753  1.0  1.8
virginica         5.552  0.551895  4.5  6.9       2.026  0.274650  1.4  2.5

           sepal_area
                 mean       std    min    max
species
setosa        17.2578  2.933775  10.35  25.08
versicolor    16.5262  2.866882  10.00  22.40
virginica     19.6846  3.458783  12.25  30.02

## Combinación de data frames

In [21]:
# Crear otro DataFrame para combinar
data2 = {
    'species': ['setosa', 'versicolor', 'virginica'],
    'color': ['blanco', 'multicolor', 'púrpura']
}
df_colores = pd.DataFrame(data2)

# Merge
print("Combinación por especie:")
pd.merge(iris, df_colores, on='species')

Combinación por especie:

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area,color
0,5.1,3.5,1.4,0.2,setosa,17.85,blanco
1,4.9,3.0,1.4,0.2,setosa,14.70,blanco
2,4.7,3.2,1.3,0.2,setosa,15.04,blanco
3,4.6,3.1,1.5,0.2,setosa,14.26,blanco
4,5.0,3.6,1.4,0.2,setosa,18.00,blanco
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,púrpura
146,6.3,2.5,5.0,1.9,virginica,15.75,púrpura
147,6.5,3.0,5.2,2.0,virginica,19.50,púrpura
148,6.2,3.4,5.4,2.3,virginica,21.08,púrpura
149,5.9,3.0,5.1,1.8,virginica,17.70,púrpura

## Operaciones con series

In [22]:
# Operaciones vectorizadas
print("Suma de longitudes:")
display(iris['sepal_length'] + iris['petal_length'])

# Aplicar funciones
print("\nLongitud de sépalo redondeada:")
display(iris['sepal_length'].apply(lambda x: round(x, 1)))

# Mapear valores
print("\nMapeo de especies a códigos:")
display(iris['species'].map({'setosa': 1, 'versicolor': 2, 'virginica': 3}).head(150))

Suma de longitudes:

0       6.5
1       6.3
2       6.0
3       6.1
4       6.4
       ...
145    11.9
146    11.3
147    11.7
148    11.6
149    11.0
Length: 150, dtype: float64

Longitud de sépalo redondeada:

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

Mapeo de especies a códigos:

0      1
1      1
2      1
3      1
4      1
      ..
145    3
146    3
147    3
148    3
149    3
Name: species, Length: 150, dtype: int64